# --- MAVEN specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000
evaluation_epsilon: 0.0

runner: "parallel"
batch_size_run: 1

buffer_size: 5000
# pc mode buffer_size: 500

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "maven_learner"
double_q: True
mixer: "maven"
mixing_embed_dim: 32
hyper_initialization_nonzeros: 0

mac: "maven_mac"
agent: "rnn_maven"
noise_dim: 16
noise_embedding_dim: 32

mi_loss: 0.001

discrim_size: 32
discrim_layers: 2
rnn_agg_size: 32

entropy_scaling: 0.001
bandit_buffer: 512
bandit_iters: 8
bandit_batch: 64


name: "maven"
